---
- name: Add dotnet repo
  ansible.builtin.apt:
    deb: https://packages.microsoft.com/config/{{ ansible_distribution }}/{{ ansible_distribution_major_version }}/packages-microsoft-prod.deb
    state: present
  when: (ansible_distribution|lower == 'debian') and install_dotnet

- name: Update apt repo data
  ansible.builtin.apt:
    update_cache: yes

- name: Install ansible
  ansible.builtin.apt:
    name:
      - ansible
      - ansible-core
      - ansible-lint
    state: latest

- name: Install VCS and editor
  ansible.builtin.apt:
    name:
      - git
      - vim
    state: present

- name: Install C/C++ development tools, should be able to build Python and Linux kernel from sourceS
  ansible.builtin.apt:
    name:
      - build-essential
      - perl
      - autotools-dev
      - autoconf
      - cmake
      - ninja-build
      - valgrind
      - systemtap
      - ltrace
      - strace
      - linux-headers-generic
      - bison
      - flex
      - libncurses-dev
      - gawk
      - openssl
      - libssl-dev
      - libelf-dev
      - libudev-dev
      - libpci-dev
      - libiberty-dev
      - libffi-dev
      - python3-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - curl
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - liblzma-dev
    state: latest

- name: Install LLVM toolchain
  ansible.builtin.apt:
    name:
      - clang-format
      - clang-tidy
      - clang-tools
      - clang
      - clangd
      - libc++-dev
      - libc++1
      - libc++abi-dev
      - libc++abi1
      - libclang-dev
      - libclang1
      - liblldb-dev
      - libllvm-ocaml-dev
      - libomp-dev
      - libomp5
      - lld
      - lldb
      - llvm-dev
      - llvm-runtime
      - llvm
      - python3-clang
    state: latest
  when: install_llvm

- name: Install OpenJDK
  ansible.builtin.apt:
    name:
      - maven
      - gradle
      - default-jdk
      - default-jdk-doc
      - default-jdk-headless
    state: latest
  when: install_openjdk

- name: Install Dotnet
  ansible.builtin.apt:
    name:
      - dotnet-sdk-8.0
    state: latest
  when: install_dotnet

- name: Install Golang
  ansible.builtin.apt:
    name:
      - golang-go
    state: latest
  when: install_golang
