---
- include_tasks: install-RedHat.yml
  when: ansible_os_family|lower == 'redhat'

- include_tasks: install-Debian.yml
  when: (ansible_os_family|lower == 'debian') or
        (ansible_os_family|lower == 'ubuntu')
